### ISSUE TITLE
USER STORY: Publish a Poll

### ISSUE THREAD

**Issue by JohannHelbert** [JohannHelbert/My-first-Agile-Project#4]
In order to **collect users Feedback** as an **Administrator**, I can **publish a poll**

# Acceptance Criteria:

* As an administrator, I can create a new poll with a title and description.
* The poll should allow multiple choice options for users to select from.
* I can define the duration for which the poll will be open for users to participate.
* The poll should have a clear and intuitive user interface, making it easy for users to understand and respond.

# Tasks

- [ ] Update the admin module view: the poll design  (HTML and CSS) to include date picker
- [ ] Update the Website view: show "Stay tuned, a new poll is coming soon"
- [ ] Create a JavaScript function to validate the expiry date is at least after 3 days
- [ ] Create a Job to check expired Polls every day at 11:59 PM and Hide them
- [ ] Update the controller function
- [ ] Update the unit test script
- [ ] Test the functionality

**Comment by JohannHelbert** [comment]
This is completed
